spring:
  application:
    name: starter

server:
  port: ${SERVER_PORT:8080}

app:
  jwt:
    secret: ${JWT_SECRET}
    access-exp-minutes: ${JWT_ACCESS_EXP_MINUTES:15}
    refresh-exp-days: ${JWT_REFRESH_EXP_DAYS:7}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
